### ISSUE TITLE
登录时报错

### ISSUE THREAD

**Issue by nov-11-dev** [wf1314/terminal-Zhihu#12]
![1371589187274_ pic_hd](https://user-images.githubusercontent.com/57243843/81543276-6bc3bc00-93a8-11ea-811b-95ab648742a1.jpg)

**Comment by wf1314** [comment]
使用时需要确定安装了 Node.js（7.0 以上版本） 或其他 JS 环境

在当前目录下执行: `$npm install jsdom`
